plugins:
  - jest

env:
  node: true  
  jest: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVerdion: latest

rules:
  no-console: 0 
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always